### ISSUE TITLE
Add discord notifications

### ISSUE THREAD

**Issue by Le0Developer** [Cloudflare-Mining/Cloudflare-Datamining#2]
Either by:
- adding pingable roles
- separating each product into its own dedicated channel, so users can manually overwrite their notification settings

Pingable roles have the plus of being pings, meanwhile notifications will not be specially marked in the app itself except the notification.

**Comment by Cherry** [comment]
Thanks for the suggestion! I've implemented individual channels for each product. We can re-explore individual pingable roles again in the future, but marking this as done for now.
