### ISSUE TITLE
UI Change

### ISSUE THREAD

**Issue by raviikushh** [Cloudflare-Mining/Cloudflare-Datamining#24]
- I can add toggle button to switch between dark theme.
- And fix the navbar at top and few changes
-  I'm also looking to change for good looking UI. 
- Also can add a line in the left side bar.

**Comment by Cherry** [comment]
Sure, thank you! Feel free to submit a PR and I'll be happy to review.

**Comment by raviikushh** [comment]
> Sure, thank you! Feel free to submit a PR and I'll be happy to review.

Thanks please assign me, I'll start working on it
