### ISSUE TITLE
Pages V2 Build System - rsync command not found

### ISSUE THREAD

**Issue by tddschn** [Cloudflare-Mining/Cloudflare-Datamining#34]
rsync is listed at https://cfdata.lol/products/pages/ , but it doesn't seem to be available in the Pages V2 Build System.

![CleanShot-2024-02-07T12-18-38@2x](https://github.com/Cloudflare-Mining/Cloudflare-Datamining/assets/45612704/883c45a3-d4ba-491c-8cf9-425c966f1db7)

**Comment by Cherry** [comment]
Good catch, thank you. I was using the old v1 build system for testing, and have now updated to v2.

https://github.com/Cloudflare-Mining/Cloudflare-Datamining/commit/0937335a5f6496ecd4b1fb6b253537c23923e931 for full changes.

**Comment by tddschn** [comment]
Are all packages / commands listed on https://cfdata.lol/products/pages/ ? `pipx` is available but doesn't seem to be on the page.

**Comment by Cherry** [comment]
This page lists all the packages installed, queried via dpkg. That's not necessarily going to include every command, as `pipx` is likely to be included in one of the installed python packages.
